export const countries: { [key: string]: { [key: string]: string[] } } = {
  'United States': {
    'Alabama': ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville'],
    'Alaska': ['Anchorage', 'Juneau', 'Fairbanks', 'Ketchikan'],
    'Arizona': ['Phoenix', 'Mesa', 'Chandler', 'Scottsdale'],
    'Arkansas': ['Little Rock', 'Fayetteville', 'Springdale', 'Jonesboro'],
    'California': ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento'],
    'Colorado': ['Denver', 'Colorado Springs', 'Boulder', 'Fort Collins'],
    'Connecticut': ['Bridgeport', 'New Haven', 'Hartford', 'Stamford'],
    'Delaware': ['Wilmington', 'Dover', 'Newark', 'Middletown'],
    'Florida': ['Miami', 'Tampa', 'Orlando', 'Jacksonville'],
    'Georgia': ['Atlanta', 'Augusta', 'Savannah', 'Columbus'],
    'Hawaii': ['Honolulu', 'Hilo', 'Kailua', 'Kaneohe'],
    'Idaho': ['Boise', 'Nampa', 'Meridian', 'Pocatello'],
    'Illinois': ['Chicago', 'Aurora', 'Rockford', 'Joliet'],
    'Indiana': ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend'],
    'Iowa': ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City'],
    'Kansas': ['Kansas City', 'Wichita', 'Olathe', 'Topeka'],
    'Kentucky': ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro'],
    'Louisiana': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette'],
    'Maine': ['Portland', 'Lewiston', 'Bangor', 'Augusta'],
    'Maryland': ['Baltimore', 'Columbia', 'Frederick', 'Annapolis'],
    'Massachusetts': ['Boston', 'Worcester', 'Springfield', 'Cambridge'],
    'Michigan': ['Detroit', 'Grand Rapids', 'Lansing', 'Ann Arbor'],
    'Minnesota': ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth'],
    'Mississippi': ['Jackson', 'Gulfport', 'Biloxi', 'Meridian'],
    'Missouri': ['Kansas City', 'Saint Louis', 'Springfield', 'Columbia'],
    'Montana': ['Billings', 'Missoula', 'Great Falls', 'Butte'],
    'Nebraska': ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island'],
    'Nevada': ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas'],
    'New Hampshire': ['Manchester', 'Nashua', 'Concord', 'Derry'],
    'New Jersey': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth'],
    'New Mexico': ['Albuquerque', 'Las Cruces', 'Santa Fe', 'Rio Rancho'],
    'New York': ['New York City', 'Buffalo', 'Rochester', 'Albany'],
    'North Carolina': ['Charlotte', 'Raleigh', 'Greensboro', 'Durham'],
    'North Dakota': ['Bismarck', 'Fargo', 'Grand Forks', 'Minot'],
    'Ohio': ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo'],
    'Oklahoma': ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow'],
    'Oregon': ['Portland', 'Eugene', 'Salem', 'Gresham'],
    'Pennsylvania': ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie'],
    'Rhode Island': ['Providence', 'Warwick', 'Cranston', 'Pawtucket'],
    'South Carolina': ['Charleston', 'Columbia', 'Greenville', 'Myrtle Beach'],
    'South Dakota': ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Watertown'],
    'Tennessee': ['Memphis', 'Nashville', 'Knoxville', 'Chattanooga'],
    'Texas': ['Houston', 'Dallas', 'Austin', 'San Antonio'],
    'Utah': ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan'],
    'Vermont': ['Burlington', 'Rutland', 'Montpelier', 'Barre'],
    'Virginia': ['Virginia Beach', 'Richmond', 'Arlington', 'Alexandria'],
    'Washington': ['Seattle', 'Spokane', 'Tacoma', 'Vancouver'],
    'West Virginia': ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg'],
    'Wisconsin': ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha'],
    'Wyoming': ['Cheyenne', 'Laramie', 'Casper', 'Gillette'],
  },
  'India': {
    'Andaman and Nicobar Islands': ['Port Blair', 'Diglipur', 'Mayabunder'],
    'Andhra Pradesh': ['Hyderabad', 'Visakhapatnam', 'Vijayawada', 'Tirupati'],
    'Arunachal Pradesh': ['Itanagar', 'Dibrugarh', 'Tawang'],
    'Assam': ['Guwahati', 'Silchar', 'Dibrugarh', 'Nagaon'],
    'Bihar': ['Patna', 'Gaya', 'Bhagalpur', 'Darbhanga'],
    'Chhattisgarh': ['Raipur', 'Bhilai', 'Durg', 'Bilaspur'],
    'Dadra and Nagar Haveli': ['Silvassa', 'Khanvel', 'Dadra'],
    'Daman and Diu': ['Daman', 'Diu', 'Nani Daman'],
    'Delhi': ['New Delhi', 'Delhi Cantonment', 'Dwarka', 'Greater Noida'],
    'Goa': ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa'],
    'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot'],
    'Haryana': ['Faridabad', 'Gurgaon', 'Hisar', 'Rohtak'],
    'Himachal Pradesh': ['Shimla', 'Solan', 'Mandi', 'Kangra'],
    'Jharkhand': ['Ranchi', 'Dhanbad', 'Giridih', 'Bokaro'],
    'Karnataka': ['Bangalore', 'Mysore', 'Mangalore', 'Hubli'],
    'Kerala': ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Kottayam'],
    'Lakshadweep': ['Kavaratti', 'Minicoy', 'Agatti'],
    'Madhya Pradesh': ['Indore', 'Bhopal', 'Jabalpur', 'Gwalior'],
    'Maharashtra': ['Mumbai', 'Pune', 'Nagpur', 'Ahmedabad'],
    'Manipur': ['Imphal', 'Thoubal', 'Bishnupur'],
    'Meghalaya': ['Shillong', 'Tura', 'Jowai'],
    'Mizoram': ['Aizawl', 'Lunglei', 'Saiha'],
    'Nagaland': ['Kohima', 'Dimapur', 'Mokokchung'],
    'Odisha': ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur'],
    'Puducherry': ['Puducherry', 'Yanam', 'Mahe', 'Karaikal'],
    'Punjab': ['Chandigarh', 'Ludhiana', 'Amritsar', 'Jalandhar'],
    'Rajasthan': ['Jaipur', 'Jodhpur', 'Ajmer', 'Udaipur'],
    'Sikkim': ['Gangtok', 'Pelling', 'Namchi'],
    'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Salem'],
    'Telangana': ['Hyderabad', 'Warangal', 'Karimnagar', 'Khammam'],
    'Tripura': ['Agartala', 'Udaipur', 'Dharmanagar'],
    'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Varanasi', 'Agra'],
    'Uttarakhand': ['Dehradun', 'Haridwar', 'Nainital', 'Almora'],
    'West Bengal': ['Kolkata', 'Asansol', 'Siliguri', 'Durgapur'],
  },
  'Canada': {
    'Alberta': ['Calgary', 'Edmonton', 'Lethbridge', 'Red Deer'],
    'British Columbia': ['Vancouver', 'Victoria', 'Kelowna', 'Surrey'],
    'Manitoba': ['Winnipeg', 'Brandon', 'Thompson', 'Portage la Prairie'],
    'New Brunswick': ['Saint John', 'Moncton', 'Fredericton', 'Bathurst'],
    'Newfoundland and Labrador': ['St. John\'s', 'Corner Brook', 'Gander', 'Grand Falls'],
    'Northwest Territories': ['Yellowknife', 'Hay River', 'Inuvik'],
    'Nova Scotia': ['Halifax', 'Cape Breton', 'Glace Bay', 'Sydney'],
    'Nunavut': ['Iqaluit', 'Rankin Inlet', 'Arviat'],
    'Ontario': ['Toronto', 'Ottawa', 'Hamilton', 'London'],
    'Prince Edward Island': ['Charlottetown', 'Summerside', 'Stratford'],
    'Quebec': ['Montreal', 'Quebec City', 'Gatineau', 'Laval'],
    'Saskatchewan': ['Saskatoon', 'Regina', 'Prince Albert', 'Moose Jaw'],
    'Yukon': ['Whitehorse', 'Watson Lake', 'Dawson City'],
  },
  'United Kingdom': {
    'England': ['London', 'Manchester', 'Birmingham', 'Leeds'],
    'Scotland': ['Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee'],
    'Wales': ['Cardiff', 'Swansea', 'Newport', 'Wrexham'],
    'Northern Ireland': ['Belfast', 'Derry', 'Lisburn', 'Newry'],
  },
  'Australia': {
    'New South Wales': ['Sydney', 'Newcastle', 'Wollongong', 'Central Coast'],
    'Victoria': ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo'],
    'Queensland': ['Brisbane', 'Gold Coast', 'Sunshine Coast', 'Cairns'],
    'South Australia': ['Adelaide', 'Mount Barker', 'Gawler', 'Port Augusta'],
    'Western Australia': ['Perth', 'Fremantle', 'Mandurah', 'Bunbury'],
    'Tasmania': ['Hobart', 'Launceston', 'Devonport', 'Burnie'],
    'Australian Capital Territory': ['Canberra', 'Belconnen', 'Tuggeranong'],
    'Northern Territory': ['Darwin', 'Alice Springs', 'Palmerston'],
  },
};

export const getCountries = () => Object.keys(countries);
export const getStates = (country: string) => Object.keys(countries[country] || {});
export const getCities = (country: string, state: string) => countries[country]?.[state] || [];
